@hostname = localhost
@port = 6978
@host = {{hostname}}:{{port}}

### GET TOKEN
POST http://{{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "login": "login",
    "password": "password"
}

### get user by id
GET http://{{host}}/user/get/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJ1c2VySWQiOjEsInJvbGVJZCI6Mn0sImlhdCI6MTY2NzAzNzY0OSwiZXhwIjoxNjY3MDQ0ODQ5fQ.9xtgUMY4uzG1EKQnFEvPe_DbqEhyzO3lvzC8ewzwuX8

### update user by id
PUT http://{{host}}/user/get/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJ1c2VySWQiOjEsInJvbGVJZCI6Mn0sImlhdCI6MTY2NzAzNzY0OSwiZXhwIjoxNjY3MDQ0ODQ5fQ.9xtgUMY4uzG1EKQnFEvPe_DbqEhyzO3lvzC8ewzwuX8

### create user
POST http://{{host}}/user/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJ1c2VySWQiOjEsInJvbGVJZCI6MX0sImlhdCI6MTY2NzA0MTAzOCwiZXhwIjoxNjY3MDQ4MjM4fQ.pzewd9c__K3HR8h93LYZYJqhOz486XV8LqN2IKIjIMg

{
    "firstName": "firstName",
    "lastName": "lastName",
    "login": "login66",
    "password": "password266"
}